	[CommonSettings.TARDIS]
		#List of Dimensions that will not be displayed in the TARDIS Dimensions List
		#Example: minecraft:the_end
		dimensionsBlacklist = ["immersive_portals:alternate1", "immersive_portals:alternate2", "immersive_portals:alternate3", "immersive_portals:alternate4", "immersive_portals:alternate5", "ae2:spatial_storage"]
		#Hide The End from the TARDIS Dimensions List until the Dragon is defeated
		hideTheEndConditionally = true
		#Allow only operators to recall the TARDIS by key
		tardisRecallOperatorOnly = false
		#Allows you to visit any dimension without having to visit them first
		dimensionsAlwaysAvailable = false
		#Allows you to visit any biome without having to visit them first
		biomesAlwaysAvailable = false
		#Allows you to visit any structure without having to visit them first
		structuresAlwaysAvailable = false
		#Allows you to visit any structure without having to visit them first
		filterStructuresByVisitedBiomes = true
