#===============================================
#
#
#Project MMO is primarily configured with datapacks.
#you can generate one via in-game commands
#start by running '/pmmo genData begin' to clear any previous settings
#then run         '/pmmo genData withConfigs' to include the settings typically found in server configs
#then run         '/pmmo genData create' to have a new datapack created in your world's datapacks folder
#
#Under every mod id, you will find pmmo folders with files for all of the items/blocks/entities in the game.
#Under '/data/pmmo/configs/' are all of the server configs for things like xp, mob scaling, and AutoValues
#
#If you are not fond of datapacks, PMMO also provides a script-like option via '.pmmo' files.
#If you would like more information on scripting or more details on the datapack configs, please check out the wiki
#https://moddedmc.wiki/en/project/pmmo/1.21.1/docs
#
#
#===============================================
[Common]

	#PMMO Error Logging Configuration
	#
	#===================================================
	#To enable Logging with MsLoggy, enter a logging
	#keyword into the logging level list that you want.
	#the list of keywords are (lowercase only):
	#'api', 'autovalues', 'chunk', 'data', 'event', 
	#'feature', 'gui', 'loading', 'network', 'req', and 'xp'
	#===================================================
	[Common."Ms Loggy"]
		#Which MsLoggy info logging should be enabled?  This will flood your log with data, but provides essential details
		# when trying to find data errors and bug fixing.  
		"Info Logging" = ["loading", "network", "api"]
		#Which MsLoggy debug logging should be enabled?  This will flood your log with data, but provides essential details
		# when trying to find bugs. DEVELOPER SETTING (mostly).  
		"Debug Logging" = ["autovalues"]
		#Which MsLoggy warn logging should be enabled?  This log type is helpful for catching important but non-fatal issues
		"Warn Logging" = ["api"]
		#Which Error Logging should be enabled.  it is highly recommended this stay true.  however, you can
		#disable it to remove pmmo errors from the log.
		"Error Logging" = ["data", "api"]
		#Which MsLoggy fatal logging should be enabled?  I can't imagine a situation where you'd want this off, but here you go.
		"Fatal Logging" = ["api"]
